apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vault-agent
  labels:
    app: vault-agent
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vault-agent
    spec:
      serviceAccountName: vault-agent
      containers:
        - name: vault-agent
          image: hashicorp/vault-agent:0.0.1
          imagePullPolicy: IfNotPresent
          env:
          - name: VAULT_ADDR
            value: http://vault:8200
          - name: VAULT_SECRET_DB_USERNAME
            value: "secret/demo:/vault/secrets/db-username"
          - name: VAULT_SECRET_DB_PASSWORD
            value: "secret/demo:/vault/secrets/db-password"
          volumeMounts:
            - name: vault-secrets
              mountPath: /vault/secrets
              readOnly: false
      volumes:
        - name: vault-secrets
          emptyDir: {}
